### ISSUE TITLE
Sobre utilização da biblioteca para projeto Web

### ISSUE THREAD

**Issue by mozgbrasil** [FlamingoJS/is-cpf#1]
Boa Tarde

Ola tudo bom

Gostaria de estar efetuando testes com a sua biblioteca

Como eu utilizo a mesma ?

Executei o comando em meu terminal e foi criado uma pasta node_modules

Pretendo usar em um projeto para a Web

**Comment by mozgbrasil** [comment]
Executei os seguintes comandos

cd Downloads

npm init --yes

npm ls

npm install --save cpf

node main.js

# 

Criei arquivo main.js contendo a forma de uso que você descreveu

Ao executar o ultimo comando é retornado no terminal

## 

module.js:328
    throw err;
    ^

Error: Cannot find module 'is-cpf'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/main.js:1:77)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

**Comment by mozgbrasil** [comment]
Desconsidere minha ultima interação

**Comment by brunoqueiros** [comment]
@mozgbrasil para instalar rode `npm install --save is-cpf`
e para utilizar você tem que passar o valor que deseja validar como parametro.
https://github.com/FlamingoJS/is-cpf#usage
